# Generated by Django 2.2.8 on 2020-01-30 08:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200129_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='blogs.Category', verbose_name='التصنيفات'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='المقال'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='المميز'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.TextField(blank=True, verbose_name='المقدمة'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='post_thumbnail/', verbose_name='صورة المقال'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان المقال'),
        ),
    ]
