# Generated by Django 2.2.8 on 2020-01-30 08:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200130_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='timestamp', unique_with=('timestamp',)),
        ),
    ]
