# Generated by Django 2.2.8 on 2020-03-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'استمارة التواصل', 'verbose_name_plural': 'استمارة التواصل'},
        ),
    ]
