# Generated by Django 2.2.8 on 2020-03-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200304_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='بريدك الالكتروني'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, verbose_name='كتابة الرسالة'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم بالكامل'),
        ),
    ]
