# Generated by Django 2.2.8 on 2020-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200304_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(null=True, verbose_name='كتابة الرسالة'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='الاسم بالكامل'),
        ),
    ]
